title: Catrobat
description: A visual programming language and set of creativity tools
url: https://developer.catrobat.org/
repository: Catrobat/catrobat.github.com
theme: just-the-docs

logo: "/assets/images/catrobat_logo.svg"
favicon_ico: "/assets/images/favicon.ico"

permalink: pretty

aux_links:
  "Main Website":
    - "https://catrobat.org/"
  "Get our Apps":
    - "https://catrobat.org/our-apps/"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - fixtures/

search_enabled: true
enable_copy_code_button: true
heading_anchors: true
aux_links_new_tab: true

# Navigation external links
nav_external_links:
  - title: GitHub
    url: https://github.com/Catrobat
  - title: Project statistics
    url: https://www.openhub.net/p/catrobat

# Footer
back_to_top: true
back_to_top_text: "Back to top"

last_edit_timestamp: false # leave disabled, we have our own solution
last_edit_time_format: "%D" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

gh_edit_link: false # leave disabled, we have our own solution
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/Catrobat/catrobat.github.com" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: dark

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
